# TODO: should allow local and group config, like .ayi.yml .ayi.local.yml
debug: true
test:
    - sh -c "go test -v -cover $(glide novendor)"
install:
    - go install
update:
    - glide update    
user: example-user
project:
    name: example
    src: https://github.com/ex/exx
runtime-deps:
    - node
    - php
# the follow configs are user wide, should be put in ~/.ayi.yml
git:
    repositories: /home/at15/repos
    hosts:
        # host without name attribute should be skipped
        - port: 1997
          https: false
        - name: git.saber.io
          port: 10086
          https: false
        - name: git.pika.io
          port: 10086
          https: true
scripts:
    mie: echo mie
    qian:
        - echo showing off
        - echo aha