debug: true
test:
    - sh -c "go test -v -cover $(glide novendor)"
install:
    - go install   
update:
    - glide update    
user: example-user
project:
    name: example
    src: https://github.com/ex/exx
runtime-deps:
    - node
    - php
# the follow configs are user wide, should be put in ~/.ayi.yml
git:
    hosts:
        # host without name attribute should be skipped
        - port: 1997
          https: false
        - name: git.saber.io
          port: 10086
          https: false
        - name: git.pika.io
          port: 10086
          https: true