debug: true
test:
    # FIXME: why sh is needed.... why can't just run the script
    - sh ./scripts/test.sh
user: example-user
project:
    name: example
    src: https://github.com/ex/exx
runtime-deps:
    - node
    - php