debug: true
dep-install:
    - go get github.com/at15/go.rice/rice
    - go get github.com/mitchellh/gox
    - glide install
install:
    - go build -o Ayi
# disable it for now
#    - rice append -i github.com/dyweb/Ayi/app/web --exec Ayi
    - sh -c "mv Ayi $GOPATH/bin/Ayi"
test:
    - go install
    - sh -c "go test -v -cover $(glide novendor)"
scripts:
    build: gox -output="build/Ayi_{{.OS}}_{{.Arch}}"
    # for test logging stdout (failed ...)
    clone:
     - git clone git@github.com:xephon-contrib/hey.git
     - rm -rf hey
    mie: echo mie
    ls: ls