version: 2

requirements:
  signed_off_by:
    required: false

always_pending:
  title_regex: 'WIP'
  explanation: 'Work in progress...'

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^:\+1:|^LGTM|^lgtm'
  reset_on_push:
    enabled: true

groups:
  code-review:
    required: 1
    users:
      - at15
      - gaocegege
