language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/pierrre/gotestcover

script:
  - go test -v ./...
  - gotestcover -coverprofile=cover.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)