# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# the latest release v15.0.0 was released on Jan 2018
[[constraint]]
  name = "github.com/google/go-github"
  branch = "master"

# as a dywegb go project, testing out master branch of its dependencies is .. well integration test
[[constraint]]
  name = "github.com/dyweb/gommon"
  branch = "master"

[[constraint]]
  name = "github.com/dyweb/go.ice"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
